# Generated by Django 2.2.7 on 2019-12-12 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20191210_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_video',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='course', verbose_name='封面视频'),
        ),
        migrations.AlterField(
            model_name='coursepricediscount',
            name='active',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='activecourses', to='course.Activity', verbose_name='活动'),
        ),
        migrations.AlterField(
            model_name='coursepricediscount',
            name='discount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discountcourse', to='course.CourseDiscount', verbose_name='优惠折扣'),
        ),
    ]
