# Generated by Django 2.2.7 on 2019-12-10 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='coupon',
            field=models.IntegerField(default=0, null=True, verbose_name='用户优惠券ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='credit',
            field=models.IntegerField(default=0, null=True, verbose_name='使用的积分数量'),
        ),
    ]
